[tool.pytest.ini_options]
filterwarnings = ["ignore:numpy.ndarray size changed:RuntimeWarning"]

[tool.ruff]
line-length = 79
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]
